# Generated by Django 5.0.6 on 2024-05-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient', models.CharField(max_length=500, verbose_name='Клиент')),
                ('number', models.CharField(max_length=500, verbose_name='Номер заказчика')),
                ('email', models.EmailField(max_length=500, verbose_name='Почта')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('Выполнен', 'Выполнен'), ('В работе', 'В работе'), ('Новый', 'Новый')], verbose_name='Статус заказа')),
            ],
        ),
    ]
